const FONT_STACKS = Object.freeze({
  figtree: '"Figtree", "Segoe UI", sans-serif',
  inter: '"Inter", "Segoe UI", sans-serif',
  manrope: '"Manrope", "Segoe UI", sans-serif',
  merriweather: '"Merriweather", Georgia, serif',
  notoSans: '"Noto Sans", "Segoe UI", sans-serif',
  outfit: '"Outfit", "Segoe UI", sans-serif',
  sourceSans: '"Source Sans 3", "Segoe UI", sans-serif',
  sourceSerif: '"Source Serif 4", Georgia, serif',
});

const BASE_THEME_VARIABLES = Object.freeze({
  "--font-heading": FONT_STACKS.figtree,
  "--font-body": FONT_STACKS.notoSans,
  "--color-bg-primary": "#f8fafc",
  "--color-bg-secondary": "#ffffff",
  "--color-header-bg": "rgba(255, 255, 255, 0.85)",
  "--color-text-primary": "#0f172a",
  "--color-text-secondary": "#475569",
  "--color-text-muted": "#64748b",
  "--color-accent": "#10b981",
  "--color-accent-hover": "#059669",
  "--color-accent-soft": "rgba(16, 185, 129, 0.12)",
  "--color-accent-text": "#ffffff",
  "--color-emphasis": "#047857",
  "--color-emphasis-strong": "#064e3b",
  "--color-border": "rgba(15, 23, 42, 0.1)",
  "--color-correct": "#34d399",
  "--color-correct-hover": "#10b981",
  "--color-wrong": "#f87171",
  "--color-wrong-hover": "#ef4444",
  "--color-focus-ring": "rgba(16, 185, 129, 0.32)",
  "--screen-glow": "rgba(16, 185, 129, 0.14)",
});

function createThemePreset({
  label,
  colorScheme = "light",
  variables = {},
}) {
  return Object.freeze({
    label,
    colorScheme,
    variables: Object.freeze({
      ...BASE_THEME_VARIABLES,
      ...variables,
    }),
  });
}

export const THEME_PRESETS = Object.freeze({
  light: createThemePreset({
    label: "Aydınlık",
  }),
  midnight: createThemePreset({
    label: "Karanlık",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.figtree,
      "--font-body": FONT_STACKS.notoSans,
      "--color-bg-primary": "#040405",
      "--color-bg-secondary": "#101012",
      "--color-header-bg": "rgba(16, 16, 18, 0.92)",
      "--color-text-primary": "#e4e4e7",
      "--color-text-secondary": "#a1a1aa",
      "--color-text-muted": "#71717a",
      "--color-accent": "#52525b",
      "--color-accent-hover": "#3f3f46",
      "--color-accent-soft": "rgba(161, 161, 170, 0.16)",
      "--color-emphasis": "#f5c451",
      "--color-emphasis-strong": "#ffffff",
      "--color-border": "#454550",
      "--color-correct": "#34d399",
      "--color-correct-hover": "#10b981",
      "--color-wrong": "#fb7185",
      "--color-wrong-hover": "#f43f5e",
      "--color-focus-ring": "rgba(245, 196, 81, 0.38)",
      "--screen-glow": "rgba(245, 196, 81, 0.1)",
    },
  }),
  ember: createThemePreset({
    label: "Amber",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.manrope,
      "--font-body": FONT_STACKS.sourceSans,
      "--color-bg-primary": "#191511",
      "--color-bg-secondary": "#241d18",
      "--color-header-bg": "rgba(36, 29, 24, 0.9)",
      "--color-text-primary": "#f5ede3",
      "--color-text-secondary": "#d2c2b3",
      "--color-text-muted": "#b9a799",
      "--color-accent": "#c97a33",
      "--color-accent-hover": "#dc8b40",
      "--color-accent-soft": "rgba(201, 122, 51, 0.16)",
      "--color-emphasis": "#e3b069",
      "--color-emphasis-strong": "#f1d19f",
      "--color-border": "rgba(241, 209, 159, 0.14)",
      "--color-focus-ring": "rgba(227, 176, 105, 0.36)",
      "--screen-glow": "rgba(227, 176, 105, 0.14)",
    },
  }),
  dark: createThemePreset({
    label: "Mavi",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.outfit,
      "--font-body": FONT_STACKS.inter,
      "--color-bg-primary": "#0f172a",
      "--color-bg-secondary": "#1e293b",
      "--color-header-bg": "rgba(30, 41, 59, 0.88)",
      "--color-text-primary": "#f8fafc",
      "--color-text-secondary": "#94a3b8",
      "--color-text-muted": "#7f9ab3",
      "--color-accent": "#4f8cff",
      "--color-accent-hover": "#3b74ea",
      "--color-accent-soft": "rgba(79, 140, 255, 0.18)",
      "--color-emphasis": "#c4b5fd",
      "--color-emphasis-strong": "#e9d5ff",
      "--color-border": "rgba(255, 255, 255, 0.1)",
      "--color-focus-ring": "rgba(79, 140, 255, 0.4)",
      "--screen-glow": "rgba(79, 140, 255, 0.18)",
    },
  }),
  "ocean-depths": createThemePreset({
    label: "Ocean Depths",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.figtree,
      "--font-body": FONT_STACKS.sourceSans,
      "--color-bg-primary": "#0b1120",
      "--color-bg-secondary": "#112240",
      "--color-header-bg": "rgba(17, 34, 64, 0.88)",
      "--color-text-primary": "#e0f2fe",
      "--color-text-secondary": "#7dd3fc",
      "--color-text-muted": "#bae6fd",
      "--color-accent": "#06b6d4",
      "--color-accent-hover": "#0891b2",
      "--color-accent-soft": "rgba(6, 182, 212, 0.18)",
      "--color-emphasis": "#67e8f9",
      "--color-emphasis-strong": "#ecfeff",
      "--color-border": "rgba(125, 211, 252, 0.18)",
      "--screen-glow": "rgba(34, 211, 238, 0.18)",
    },
  }),
  "sunset-boulevard": createThemePreset({
    label: "Sunset Boulevard",
    variables: {
      "--font-heading": FONT_STACKS.merriweather,
      "--font-body": FONT_STACKS.sourceSans,
      "--color-bg-primary": "#fff7ed",
      "--color-bg-secondary": "#ffedd5",
      "--color-header-bg": "rgba(255, 237, 213, 0.85)",
      "--color-text-primary": "#7c2d12",
      "--color-text-secondary": "#c2410c",
      "--color-text-muted": "#9a3412",
      "--color-accent": "#f97316",
      "--color-accent-hover": "#ea580c",
      "--color-accent-soft": "rgba(249, 115, 22, 0.14)",
      "--color-emphasis": "#fb7185",
      "--color-emphasis-strong": "#be123c",
      "--color-border": "rgba(194, 65, 12, 0.16)",
      "--screen-glow": "rgba(251, 146, 60, 0.18)",
    },
  }),
  "forest-canopy": createThemePreset({
    label: "Forest Canopy",
    variables: {
      "--font-heading": FONT_STACKS.merriweather,
      "--font-body": FONT_STACKS.notoSans,
      "--color-bg-primary": "#f0fdf4",
      "--color-bg-secondary": "#dcfce7",
      "--color-header-bg": "rgba(220, 252, 231, 0.88)",
      "--color-text-primary": "#14532d",
      "--color-text-secondary": "#166534",
      "--color-text-muted": "#15803d",
      "--color-accent": "#16a34a",
      "--color-accent-hover": "#15803d",
      "--color-accent-soft": "rgba(22, 163, 74, 0.14)",
      "--color-emphasis": "#65a30d",
      "--color-emphasis-strong": "#3f6212",
      "--color-border": "rgba(21, 128, 61, 0.16)",
    },
  }),
  "modern-minimalist": createThemePreset({
    label: "Modern Minimalist",
    variables: {
      "--font-heading": FONT_STACKS.manrope,
      "--font-body": FONT_STACKS.inter,
      "--color-bg-primary": "#fafaf9",
      "--color-bg-secondary": "#ffffff",
      "--color-header-bg": "rgba(255, 255, 255, 0.92)",
      "--color-text-primary": "#1c1917",
      "--color-text-secondary": "#57534e",
      "--color-text-muted": "#78716c",
      "--color-accent": "#18181b",
      "--color-accent-hover": "#27272a",
      "--color-accent-soft": "rgba(39, 39, 42, 0.08)",
      "--color-emphasis": "#0ea5e9",
      "--color-emphasis-strong": "#0369a1",
      "--color-border": "rgba(24, 24, 27, 0.1)",
    },
  }),
  "golden-hour": createThemePreset({
    label: "Golden Hour",
    variables: {
      "--font-heading": FONT_STACKS.sourceSerif,
      "--font-body": FONT_STACKS.sourceSans,
      "--color-bg-primary": "#fffbeb",
      "--color-bg-secondary": "#fef3c7",
      "--color-header-bg": "rgba(254, 243, 199, 0.88)",
      "--color-text-primary": "#78350f",
      "--color-text-secondary": "#92400e",
      "--color-text-muted": "#b45309",
      "--color-accent": "#f59e0b",
      "--color-accent-hover": "#d97706",
      "--color-accent-soft": "rgba(245, 158, 11, 0.14)",
      "--color-emphasis": "#eab308",
      "--color-emphasis-strong": "#854d0e",
      "--color-border": "rgba(180, 83, 9, 0.14)",
    },
  }),
  "arctic-frost": createThemePreset({
    label: "Arctic Frost",
    variables: {
      "--font-heading": FONT_STACKS.figtree,
      "--font-body": FONT_STACKS.inter,
      "--color-bg-primary": "#f8fafc",
      "--color-bg-secondary": "#e2e8f0",
      "--color-header-bg": "rgba(226, 232, 240, 0.82)",
      "--color-text-primary": "#0f172a",
      "--color-text-secondary": "#334155",
      "--color-text-muted": "#475569",
      "--color-accent": "#38bdf8",
      "--color-accent-hover": "#0ea5e9",
      "--color-accent-soft": "rgba(56, 189, 248, 0.16)",
      "--color-emphasis": "#6366f1",
      "--color-emphasis-strong": "#4338ca",
      "--color-border": "rgba(51, 65, 85, 0.12)",
    },
  }),
  "desert-rose": createThemePreset({
    label: "Desert Rose",
    variables: {
      "--font-heading": FONT_STACKS.sourceSerif,
      "--font-body": FONT_STACKS.notoSans,
      "--color-bg-primary": "#fff1f2",
      "--color-bg-secondary": "#ffe4e6",
      "--color-header-bg": "rgba(255, 228, 230, 0.86)",
      "--color-text-primary": "#881337",
      "--color-text-secondary": "#9f1239",
      "--color-text-muted": "#be185d",
      "--color-accent": "#fb7185",
      "--color-accent-hover": "#f43f5e",
      "--color-accent-soft": "rgba(251, 113, 133, 0.16)",
      "--color-emphasis": "#c026d3",
      "--color-emphasis-strong": "#86198f",
      "--color-border": "rgba(190, 24, 93, 0.14)",
    },
  }),
  "tech-innovation": createThemePreset({
    label: "Tech Innovation",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.outfit,
      "--font-body": FONT_STACKS.inter,
      "--color-bg-primary": "#020617",
      "--color-bg-secondary": "#111827",
      "--color-header-bg": "rgba(17, 24, 39, 0.9)",
      "--color-text-primary": "#e5f9ff",
      "--color-text-secondary": "#67e8f9",
      "--color-text-muted": "#a5f3fc",
      "--color-accent": "#22d3ee",
      "--color-accent-hover": "#06b6d4",
      "--color-accent-soft": "rgba(34, 211, 238, 0.18)",
      "--color-emphasis": "#818cf8",
      "--color-emphasis-strong": "#c7d2fe",
      "--color-border": "rgba(103, 232, 249, 0.18)",
      "--screen-glow": "rgba(34, 211, 238, 0.18)",
    },
  }),
  "botanical-garden": createThemePreset({
    label: "Botanical Garden",
    variables: {
      "--font-heading": FONT_STACKS.merriweather,
      "--font-body": FONT_STACKS.notoSans,
      "--color-bg-primary": "#f7fee7",
      "--color-bg-secondary": "#ecfccb",
      "--color-header-bg": "rgba(236, 252, 203, 0.88)",
      "--color-text-primary": "#365314",
      "--color-text-secondary": "#4d7c0f",
      "--color-text-muted": "#65a30d",
      "--color-accent": "#84cc16",
      "--color-accent-hover": "#65a30d",
      "--color-accent-soft": "rgba(132, 204, 22, 0.14)",
      "--color-emphasis": "#10b981",
      "--color-emphasis-strong": "#047857",
      "--color-border": "rgba(77, 124, 15, 0.14)",
    },
  }),
  "midnight-galaxy": createThemePreset({
    label: "Midnight Galaxy",
    colorScheme: "dark",
    variables: {
      "--font-heading": FONT_STACKS.sourceSerif,
      "--font-body": FONT_STACKS.notoSans,
      "--color-bg-primary": "#111827",
      "--color-bg-secondary": "#1f2937",
      "--color-header-bg": "rgba(31, 41, 55, 0.88)",
      "--color-text-primary": "#f9fafb",
      "--color-text-secondary": "#c4b5fd",
      "--color-text-muted": "#ddd6fe",
      "--color-accent": "#8b5cf6",
      "--color-accent-hover": "#7c3aed",
      "--color-accent-soft": "rgba(139, 92, 246, 0.2)",
      "--color-emphasis": "#f472b6",
      "--color-emphasis-strong": "#fbcfe8",
      "--color-border": "rgba(196, 181, 253, 0.18)",
      "--screen-glow": "rgba(244, 114, 182, 0.16)",
    },
  }),
});

export const ORDERED_THEMES = Object.freeze(Object.keys(THEME_PRESETS));
export const AVAILABLE_THEMES = ORDERED_THEMES;

export function getThemePreset(themeName) {
  return THEME_PRESETS[themeName] || THEME_PRESETS.light;
}
